
project_id = "ayqsgubaggljcoqftfyz"

[functions.get-secrets]
verify_jwt = true

[functions.process-dataset]
verify_jwt = true

[functions.export-data]
verify_jwt = true

[functions.data-quality-check]
verify_jwt = true
