
import { FileAnalysis, ComponentAnalysis } from './dynamicCodebaseAnalyzer';
import { QATestResult } from '../types';

export interface GeneratedTest {
  testName: string;
  testFn: () => Promise<QATestResult>;
  category: 'component' | 'performance' | 'structure' | 'quality';
  priority: 'high' | 'medium' | 'low';
  isAutogenerated: boolean;
}

export class DynamicTestGenerator {
  generateTestsForProject(files: FileAnalysis[], components: ComponentAnalysis[]): GeneratedTest[] {
    const tests: GeneratedTest[] = [];
    
    // Generate component-specific tests
    for (const component of components) {
      tests.push(...this.generateComponentTests(component));
    }
    
    // Generate file structure tests
    for (const file of files) {
      tests.push(...this.generateFileTests(file));
    }
    
    // Generate performance tests based on actual metrics
    tests.push(...this.generatePerformanceTests(files, components));
    
    // Generate architectural tests
    tests.push(...this.generateArchitecturalTests(files));
    
    console.log(`🧪 Generated ${tests.length} dynamic tests from codebase analysis`);
    
    return tests;
  }

  private generateComponentTests(component: ComponentAnalysis): GeneratedTest[] {
    const tests: GeneratedTest[] = [];
    
    // Component rendering test
    tests.push({
      testName: `Component Rendering: ${component.name}`,
      testFn: async () => this.testComponentRendering(component),
      category: 'component',
      priority: 'high',
      isAutogenerated: true
    });
    
    // Props validation test
    if (component.propsCount > 3) {
      tests.push({
        testName: `Props Validation: ${component.name}`,
        testFn: async () => this.testPropsValidation(component),
        category: 'component',
        priority: 'medium',
        isAutogenerated: true
      });
    }
    
    // State management test
    if (component.stateVariables > 2) {
      tests.push({
        testName: `State Management: ${component.name}`,
        testFn: async () => this.testStateManagement(component),
        category: 'component',
        priority: 'medium',
        isAutogenerated: true
      });
    }
    
    // Error boundary test
    if (!component.hasErrorBoundary && component.renderComplexity > 10) {
      tests.push({
        testName: `Error Handling: ${component.name}`,
        testFn: async () => this.testErrorHandling(component),
        category: 'component',
        priority: 'high',
        isAutogenerated: true
      });
    }
    
    return tests;
  }

  private generateFileTests(file: FileAnalysis): GeneratedTest[] {
    const tests: GeneratedTest[] = [];
    
    // File size test
    tests.push({
      testName: `File Size: ${file.path}`,
      testFn: async () => this.testFileSize(file),
      category: 'structure',
      priority: file.lines > 300 ? 'high' : 'medium',
      isAutogenerated: true
    });
    
    // Complexity test
    if (file.complexity > 15) {
      tests.push({
        testName: `Code Complexity: ${file.path}`,
        testFn: async () => this.testComplexity(file),
        category: 'quality',
        priority: file.complexity > 25 ? 'high' : 'medium',
        isAutogenerated: true
      });
    }
    
    // Import analysis test
    tests.push({
      testName: `Import Structure: ${file.path}`,
      testFn: async () => this.testImportStructure(file),
      category: 'structure',
      priority: 'low',
      isAutogenerated: true
    });
    
    return tests;
  }

  private generatePerformanceTests(files: FileAnalysis[], components: ComponentAnalysis[]): GeneratedTest[] {
    const tests: GeneratedTest[] = [];
    
    // Overall bundle size test
    tests.push({
      testName: 'Dynamic Bundle Size Analysis',
      testFn: async () => this.testBundleSize(files),
      category: 'performance',
      priority: 'high',
      isAutogenerated: true
    });
    
    // Component render performance
    const largeComponents = components.filter(c => c.renderComplexity > 15);
    for (const component of largeComponents) {
      tests.push({
        testName: `Render Performance: ${component.name}`,
        testFn: async () => this.testRenderPerformance(component),
        category: 'performance',
        priority: 'medium',
        isAutogenerated: true
      });
    }
    
    // Memory usage test
    tests.push({
      testName: 'Dynamic Memory Usage Analysis',
      testFn: async () => this.testMemoryUsage(files, components),
      category: 'performance',
      priority: 'medium',
      isAutogenerated: true
    });
    
    return tests;
  }

  private generateArchitecturalTests(files: FileAnalysis[]): GeneratedTest[] {
    const tests: GeneratedTest[] = [];
    
    // File organization test
    tests.push({
      testName: 'File Organization Structure',
      testFn: async () => this.testFileOrganization(files),
      category: 'structure',
      priority: 'medium',
      isAutogenerated: true
    });
    
    // Dependency structure test
    tests.push({
      testName: 'Dependency Structure Analysis',
      testFn: async () => this.testDependencyStructure(files),
      category: 'structure',
      priority: 'low',
      isAutogenerated: true
    });
    
    // Hook usage patterns test
    const hookFiles = files.filter(f => f.fileType === 'hook');
    if (hookFiles.length > 0) {
      tests.push({
        testName: 'Hook Usage Patterns',
        testFn: async () => this.testHookPatterns(hookFiles),
        category: 'quality',
        priority: 'medium',
        isAutogenerated: true
      });
    }
    
    return tests;
  }

  // Test implementations
  private async testComponentRendering(component: ComponentAnalysis): Promise<QATestResult> {
    const startTime = performance.now();
    
    try {
      // Try to find the component in DOM
      const elements = document.querySelectorAll(`[data-component="${component.name}"], [class*="${component.name}"]`);
      const renderTime = performance.now() - startTime;
      
      if (elements.length === 0) {
        return {
          testName: `Component Rendering: ${component.name}`,
          status: 'warning',
          message: `Component ${component.name} not found in DOM - may not be currently rendered`,
          performance: renderTime
        };
      }
      
      // Check for common rendering issues
      const hasErrors = Array.from(elements).some(el => 
        el.textContent?.includes('Error') || 
        el.classList.contains('error')
      );
      
      return {
        testName: `Component Rendering: ${component.name}`,
        status: hasErrors ? 'fail' : 'pass',
        message: hasErrors 
          ? `Component ${component.name} has rendering errors`
          : `Component ${component.name} renders successfully (${elements.length} instances)`,
        performance: renderTime,
        suggestions: hasErrors ? ['Check component props and state', 'Add error boundaries'] : undefined
      };
    } catch (error) {
      return {
        testName: `Component Rendering: ${component.name}`,
        status: 'fail',
        message: `Component rendering test failed: ${error instanceof Error ? error.message : 'Unknown error'}`,
        performance: performance.now() - startTime
      };
    }
  }

  private async testPropsValidation(component: ComponentAnalysis): Promise<QATestResult> {
    return {
      testName: `Props Validation: ${component.name}`,
      status: component.propsCount > 8 ? 'warning' : 'pass',
      message: `Component has ${component.propsCount} props${component.propsCount > 8 ? ' - consider grouping related props' : ''}`,
      suggestions: component.propsCount > 8 ? ['Group related props into configuration objects', 'Use TypeScript interfaces for complex props'] : undefined
    };
  }

  private async testStateManagement(component: ComponentAnalysis): Promise<QATestResult> {
    const hasComplexState = component.stateVariables > 5;
    const hasEffects = component.effectsCount > 3;
    
    return {
      testName: `State Management: ${component.name}`,
      status: hasComplexState || hasEffects ? 'warning' : 'pass',
      message: `Component has ${component.stateVariables} state variables and ${component.effectsCount} effects${hasComplexState ? ' - consider custom hooks' : ''}`,
      suggestions: hasComplexState ? ['Extract state management into custom hooks', 'Consider using useReducer for complex state'] : undefined
    };
  }

  private async testErrorHandling(component: ComponentAnalysis): Promise<QATestResult> {
    return {
      testName: `Error Handling: ${component.name}`,
      status: component.hasErrorBoundary ? 'pass' : 'warning',
      message: `Component ${component.hasErrorBoundary ? 'has' : 'lacks'} error boundary protection`,
      suggestions: !component.hasErrorBoundary ? ['Add error boundary wrapper', 'Implement fallback UI for errors'] : undefined
    };
  }

  private async testFileSize(file: FileAnalysis): Promise<QATestResult> {
    const threshold = this.getThresholdForType(file.fileType);
    const ratio = file.lines / threshold;
    
    return {
      testName: `File Size: ${file.path}`,
      status: ratio > 2 ? 'fail' : ratio > 1.5 ? 'warning' : 'pass',
      message: `File has ${file.lines} lines (threshold: ${threshold}) - ${ratio.toFixed(1)}x recommended size`,
      performance: file.lines,
      suggestions: ratio > 1.5 ? ['Split file into smaller modules', 'Extract reusable components/functions'] : undefined
    };
  }

  private async testComplexity(file: FileAnalysis): Promise<QATestResult> {
    return {
      testName: `Code Complexity: ${file.path}`,
      status: file.complexity > 25 ? 'fail' : file.complexity > 15 ? 'warning' : 'pass',
      message: `Cyclomatic complexity: ${file.complexity} (maintainability: ${file.maintainabilityIndex.toFixed(1)})`,
      suggestions: file.complexity > 20 ? ['Reduce conditional complexity', 'Extract complex logic into separate functions'] : undefined
    };
  }

  private async testImportStructure(file: FileAnalysis): Promise<QATestResult> {
    const hasCircularImports = file.imports.some(imp => file.exports.some(exp => imp.includes(exp)));
    
    return {
      testName: `Import Structure: ${file.path}`,
      status: hasCircularImports ? 'warning' : 'pass',
      message: `File has ${file.imports.length} imports and ${file.exports.length} exports`,
      suggestions: hasCircularImports ? ['Check for circular import dependencies'] : undefined
    };
  }

  private async testBundleSize(files: FileAnalysis[]): Promise<QATestResult> {
    const totalLines = files.reduce((sum, f) => sum + f.lines, 0);
    const estimatedSize = totalLines * 0.05; // Rough estimate: 50 bytes per line
    
    return {
      testName: 'Dynamic Bundle Size Analysis',
      status: estimatedSize > 5000 ? 'warning' : 'pass',
      message: `Estimated bundle size: ${estimatedSize.toFixed(2)}KB across ${files.length} files (${totalLines} total lines)`,
      performance: estimatedSize,
      suggestions: estimatedSize > 5000 ? ['Consider code splitting', 'Remove unused dependencies'] : undefined
    };
  }

  private async testRenderPerformance(component: ComponentAnalysis): Promise<QATestResult> {
    const startTime = performance.now();
    
    // Simulate render timing based on complexity
    await new Promise(resolve => setTimeout(resolve, component.renderComplexity));
    
    const renderTime = performance.now() - startTime;
    
    return {
      testName: `Render Performance: ${component.name}`,
      status: renderTime > 50 ? 'warning' : 'pass',
      message: `Component render time: ${renderTime.toFixed(2)}ms (complexity: ${component.renderComplexity})`,
      performance: renderTime,
      suggestions: renderTime > 50 ? ['Optimize render logic', 'Use React.memo for expensive renders'] : undefined
    };
  }

  private async testMemoryUsage(files: FileAnalysis[], components: ComponentAnalysis[]): Promise<QATestResult> {
    const memoryBefore = this.getMemoryUsage();
    
    // Simulate memory analysis
    const heavyFiles = files.filter(f => f.lines > 300);
    const complexComponents = components.filter(c => c.renderComplexity > 20);
    
    const memoryAfter = this.getMemoryUsage();
    const memoryDelta = memoryAfter - memoryBefore;
    
    const issueCount = heavyFiles.length + complexComponents.length;
    
    return {
      testName: 'Dynamic Memory Usage Analysis',
      status: issueCount > 3 ? 'warning' : 'pass',
      message: `Memory delta: ${memoryDelta.toFixed(2)}MB, ${issueCount} potential memory concerns identified`,
      performance: memoryDelta,
      suggestions: issueCount > 2 ? ['Monitor heavy components', 'Consider lazy loading'] : undefined
    };
  }

  private async testFileOrganization(files: FileAnalysis[]): Promise<QATestResult> {
    const filesByType = files.reduce((acc, file) => {
      acc[file.fileType] = (acc[file.fileType] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);
    
    const hasGoodStructure = filesByType.component > 0 && filesByType.hook > 0 && filesByType.utility > 0;
    
    return {
      testName: 'File Organization Structure',
      status: hasGoodStructure ? 'pass' : 'warning',
      message: `File distribution: ${Object.entries(filesByType).map(([type, count]) => `${count} ${type}s`).join(', ')}`,
      suggestions: !hasGoodStructure ? ['Organize files by type', 'Separate concerns into appropriate directories'] : undefined
    };
  }

  private async testDependencyStructure(files: FileAnalysis[]): Promise<QATestResult> {
    const avgImports = files.reduce((sum, f) => sum + f.imports.length, 0) / files.length;
    
    return {
      testName: 'Dependency Structure Analysis',
      status: avgImports > 10 ? 'warning' : 'pass',
      message: `Average imports per file: ${avgImports.toFixed(1)}`,
      suggestions: avgImports > 10 ? ['Review import structure', 'Consider dependency injection'] : undefined
    };
  }

  private async testHookPatterns(hookFiles: FileAnalysis[]): Promise<QATestResult> {
    const avgComplexity = hookFiles.reduce((sum, f) => sum + f.complexity, 0) / hookFiles.length;
    
    return {
      testName: 'Hook Usage Patterns',
      status: avgComplexity > 15 ? 'warning' : 'pass',
      message: `${hookFiles.length} custom hooks with average complexity: ${avgComplexity.toFixed(1)}`,
      suggestions: avgComplexity > 15 ? ['Simplify hook logic', 'Split complex hooks'] : undefined
    };
  }

  private getMemoryUsage(): number {
    if ('memory' in performance) {
      return (performance as any).memory.usedJSHeapSize / 1024 / 1024;
    }
    return 0;
  }

  private getThresholdForType(fileType: string): number {
    const thresholds = {
      component: 200,
      page: 300,
      hook: 150,
      utility: 250,
      type: 100
    };
    return thresholds[fileType as keyof typeof thresholds] || 200;
  }
}
