// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ayqsgubaggljcoqftfyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5cXNndWJhZ2dsamNvcWZ0Znl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNTk3MTEsImV4cCI6MjA2NzczNTcxMX0.y4NRac4ECiEC6wNnuCuVAjspaQzqlYwIYThk5oISqv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});